### ISSUE TITLE
Clicking start menu "options" and "exit" buttons opens Scene1

### ISSUE THREAD

**Issue by abellnoel** [nabellan1/unity-dungeon#3]
- Options shows options screen briefly, does right to left banner animation, and proceeds to Scene1
- Exit does right to left banner animation and proceeds to Scene1

NOTE: This issue is not present in https://github.com/nabellan1/unity-dungeon/commit/005cc5040c9e24910478d64ebd0c3efed74186b7

**Comment by twigmytwig** [comment]
Fixed issue by disabling transition in the main menu
